{% set name = "dynapydantic" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/dynapydantic-{{ version }}.tar.gz
  sha256: 1999710d7f33bcce74495abec2e303289b484317f8e54af971041a6b0c8b9b93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.0

test:
  imports:
    - dynapydantic
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Dyanmic pydantic models
  home: https://github.com/psalvaggio/dynapydantic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psalvaggio
