{% set name = "dynapydantic" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dynapydantic-{{ version }}.tar.gz
  sha256: f41d4d81308a7399a5a7260636e1dcb016e747ee65b5a3e1c6637dedaa517257

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.0

test:
  imports:
    - dynapydantic
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Dyanmic pydantic models
  home: https://github.com/psalvaggio/dynapydantic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psalvaggio
